### ISSUE TITLE
2023-10-07: 福知山市字猪崎

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#1]
https://telegra.ph/%E7%A6%8F%E7%9F%A5%E5%B1%B1%E5%B8%82%E5%AD%97%E7%8C%AA%E5%B4%8E-10-06-10

**Comment by kongicus** [comment]
离车站南海本线鳥取ノ荘駅800ｍ，周围超市便利店都有。

**Comment by kongicus** [comment]
离车站南海本线鳥取ノ荘駅800ｍ，周围超市便利店都有。
