### ISSUE TITLE
2023-10-10: 伊豆市佐野

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#10]
{"original_url": "https://www.athome.co.jp/kodate/6979877879/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 7000000, "location": [138.95385532103546, 34.94893157212045], "address": "伊豆市佐野", "rooms": "2LDK", "land_area": 429.0, "floor_area": 85.58, "completed_date": "2005-06", "city": "静岡県伊豆市", "description": "このログがこの価格？　伊豆高原にあったらもっと高額ですね。", "photos": ["https://telegra.ph/file/ac9c10796ca069a483853.jpg", "https://telegra.ph/file/41a60e7e1c88e14d5c072.jpg", "https://telegra.ph/file/9c0f811eed68de563da3f.jpg", "https://telegra.ph/file/cd16a5cf0786905744d3c.jpg", "https://telegra.ph/file/090f812318ac2c7ca0f0e.jpg", "https://telegra.ph/file/5e2122c13ac463935f075.jpg", "https://telegra.ph/file/54e706f0cec418354104c.jpg", "https://telegra.ph/file/7972de980047c742063c5.jpg", "https://telegra.ph/file/ba05cc0a1ea3e414a643f.jpg", "https://telegra.ph/file/943cdd7d798f618b95a0f.jpg", "https://telegra.ph/file/dc3d473acfd89db5b4848.jpg", "https://telegra.ph/file/bff65a3da5996195f090f.jpg", "https://telegra.ph/file/cd9e4229c61b98c9845ce.jpg", "https://telegra.ph/file/4cf8a989f6f8783901297.jpg", "https://telegra.ph/file/1a8bd1cdd3652e3309054.jpg"]}

**Comment by kongicus** [comment]
山里度假用的木屋。
房子到伊豆的修善寺车站16分钟车程。
旁边是个高尔夫球场，叫修善寺乡村俱乐部吧。这个小木屋山下的山谷对面是修善寺温泉和旅馆集中的那边。

卖房中介写的：
房子存在高低差，但并不会让人感到特别不便。中介都这么说了，其实就是不便吧，估计得爬几步才能上去，对于几天的度假来说还行吧。
有地下室和二楼的宽敞储藏空间，适合居住。
可以看到富士山。但在地图看了下方位，应该是站在阳台往右斜看是富士山。
周围针叶树，所以即使到了冬天，树叶也不会落下。看不到日本人喜欢的枫叶秋景。
这是伊豆市的空置房屋登记物件，可能会有一些补助金，数额不大。
