### ISSUE TITLE
2023-10-12: 茂原市中の島町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#16]
{"original_url": "https://www.athome.co.jp/kodate/1066416972/?DOWN=1&BKLISTID=001LPC&SPCD=20200600000008&sref=list_simple", "price": 16800000, "location": [140.3081926, 35.4053999], "address": "茂原市中の島町", "rooms": "5SLDK", "land_area": 259.9, "floor_area": 149.04, "completed_date": "1995-12", "city": "千葉県茂原市", "description": "【C21ベルステージです！】和風戸建住宅！リフォーム済みで綺麗なお家で新生活を始められます！閑静な住宅地でのびのびスローライフを満喫できます！書斎付きでリモートワークや趣味部屋にもお使いいただけます！", "photos": ["https://telegra.ph/file/8d93979055a31ca9050df.jpg", "https://telegra.ph/file/9fe615ca477c3cdc65e16.jpg", "https://telegra.ph/file/75d3b29fdba91c05f1a78.jpg", "https://telegra.ph/file/0dedd0125047e05b74e1b.jpg", "https://telegra.ph/file/2572778c66db4d055cbe4.jpg", "https://telegra.ph/file/20c4a06d0815fe64bc4a6.jpg", "https://telegra.ph/file/9e65bfebf11a3701d82c8.jpg", "https://telegra.ph/file/e7c5b03a12d62407e6c9e.jpg", "https://telegra.ph/file/ea5589e7cf04f29eea909.jpg", "https://telegra.ph/file/8cf224b88c88904f35860.jpg", "https://telegra.ph/file/03ef9eed6884bd788740a.jpg", "https://telegra.ph/file/10b2a6cb447f3f9b55f02.jpg", "https://telegra.ph/file/966db9ea4ffc449a51b3b.jpg", "https://telegra.ph/file/e90ed9f0ee92273c7642c.jpg", "https://telegra.ph/file/964dd081131b9911cbb8b.jpg", "https://telegra.ph/file/513d3412a44b48837e111.jpg", "https://telegra.ph/file/9f90e5e36812e156c8c3e.jpg", "https://telegra.ph/file/b63d8145f23d354cec69c.jpg", "https://telegra.ph/file/4445d32bd8e53365d9cac.jpg"]}

**Comment by kongicus** [comment]
这个房子是逛远程工作特辑逛到的。
修了27年了，2022年翻新过卫浴，外墙看起来也重新装过比较新。看了下街景，隔壁也挺大，装得挺漂亮。
适合远程工作的话就是地段差点，走路去最近的茂原站要40分钟，但这里也不是都是田的村儿里，是有都市田园那种地方，毕竟茂原也不是特别村儿，算是地方上比较大的城市。
去东京的话，外房线转京叶线要一个半小时，坐房总特急一个小时、就是有点贵。
