### ISSUE TITLE
2023-10-12: 大和郡山市城町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#17]
{"original_url": "https://www.athome.co.jp/kodate/6979015557/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 8800000, "location": [135.7692774, 34.6542349], "address": "大和郡山市城町", "rooms": "6LDK", "land_area": 220.55, "floor_area": 116.0, "completed_date": "1981-08", "city": "奈良県大和郡山市", "description": "水廻り、フローリング、クロスリフォーム済♪６ＬＤＫと大家族も安心の部屋数です。", "photos": ["https://telegra.ph/file/ec3c375eff9d65c7f2f61.jpg", "https://telegra.ph/file/7dc502d1fd2efc5ed8472.jpg", "https://telegra.ph/file/d473e93db665c3df8cefe.jpg", "https://telegra.ph/file/66152dec18ba1b48767a9.jpg", "https://telegra.ph/file/504b6e2fb75ee715c9e51.jpg", "https://telegra.ph/file/e36b25ba7e1a4ec56d7af.jpg", "https://telegra.ph/file/4da03f9c10a8f4fe64026.jpg", "https://telegra.ph/file/980c5affe21bbafe23683.jpg", "https://telegra.ph/file/767d1e28fa861deab8d54.jpg", "https://telegra.ph/file/a0d482c1b54555bee1f89.jpg", "https://telegra.ph/file/c9e2d258e7ff1d448738b.jpg", "https://telegra.ph/file/2445396a15efa5ea16494.jpg", "https://telegra.ph/file/69ae1bc5fc14aca9424f7.jpg", "https://telegra.ph/file/7910e1fe16f4617b77a96.jpg", "https://telegra.ph/file/fbd47600e6d30f12830fc.jpg", "https://telegra.ph/file/e05de2efc87f34eebde36.jpg"]}

**Comment by kongicus** [comment]
2023年3月翻新，去近铁奈良和奈良站大概开车20分钟，在城市的边缘，往西是田，但也不算在村里。
