### ISSUE TITLE
2023-10-16: 横浜市保土ケ谷区仏向町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#27]
{"original_url": "https://www.athome.co.jp/kodate/1072475346/?DOWN=4&BKLISTID=004LPC&sref=list_map", "price": 24800000, "location": [139.577527, 35.458008], "address": "横浜市保土ケ谷区仏向町", "rooms": "2SLDK", "land_area": 113.24, "floor_area": 90.67, "completed_date": "2001-12", "city": "神奈川県横浜市保土ケ谷区", "description": null, "photos": ["https://telegra.ph/file/a7d53807d8ecb0d67bd9c.jpg", "https://telegra.ph/file/808a5121520d7a21a3a71.jpg", "https://telegra.ph/file/5a15ee3fe16c24e691396.jpg", "https://telegra.ph/file/9990fd701c3fbb265d6de.jpg", "https://telegra.ph/file/de90b9aedf2090501f2b9.jpg", "https://telegra.ph/file/0bdded55add672d496042.jpg", "https://telegra.ph/file/2e2babcfadf40fc64391c.jpg", "https://telegra.ph/file/70b5147bde70a01c5760b.jpg", "https://telegra.ph/file/e8a40b779677581859d95.jpg", "https://telegra.ph/file/1bfe9fc481b35ab7ccb57.jpg", "https://telegra.ph/file/c5fd0e3c80f2d16d51f52.jpg", "https://telegra.ph/file/e67818f3ae0d17f8ca939.jpg", "https://telegra.ph/file/f717b528176375e8a32aa.jpg", "https://telegra.ph/file/9ef023c51aa693cc2bfdd.jpg", "https://telegra.ph/file/472bea0b1057c86684aea.jpg", "https://telegra.ph/file/f317469ce22002597ee58.jpg", "https://telegra.ph/file/de66c75640021d95c7ed7.jpg", "https://telegra.ph/file/3139911369a63ca3cd2e5.jpg", "https://telegra.ph/file/75eb10a40377721b76040.jpg", "https://telegra.ph/file/c487e344a7500e044521d.jpg", "https://telegra.ph/file/0134198bda9a6d93d45b8.jpg", "https://telegra.ph/file/4fcb471ba02c358ffb36e.jpg", "https://telegra.ph/file/946c41f9e8c87057eb310.jpg", "https://telegra.ph/file/635a83e225b5152128661.jpg", "https://telegra.ph/file/95a4764f0aa1c7d74cf49.jpg", "https://telegra.ph/file/7814dd04c224a337962ed.jpg"]}

**Comment by kongicus** [comment]
这个地方去横滨中心开车15分钟，坐车半个小时，挂2480万，去REINS查了一下二手房成交价，新筑这个建筑面积三千五百万多，但土地一般在100平多，没有这个大。但是是要开车才行的地方，地段不好。
