### ISSUE TITLE
2023-10-18: 山本郡八峰町八森字中浜

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#31]
{"original_url": "https://www.athome.co.jp/kodate/1077866069/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 3400000, "location": null, "address": "山本郡八峰町八森字中浜", "rooms": "6LDK", "land_area": 269.5, "floor_area": 190.45, "completed_date": "1988-01", "city": "秋田県八峰町", "description": null, "photos": ["https://telegra.ph/file/49c4c38303b4c481d755f.jpg", "https://telegra.ph/file/b425c380767658e06895e.jpg", "https://telegra.ph/file/0d17b9ef39e25aca864e5.jpg", "https://telegra.ph/file/1ca8dee4f461eda81d6bc.jpg", "https://telegra.ph/file/fca3983cde40930dcd4e5.jpg", "https://telegra.ph/file/5d80329411337bd015943.jpg", "https://telegra.ph/file/25128055ab97680ffc128.jpg", "https://telegra.ph/file/5f320fcc7a5f9aa60e5b7.jpg", "https://telegra.ph/file/ff913c2b9d7e7e41be0bc.jpg", "https://telegra.ph/file/aed85c9a8572dc76e7f2a.jpg", "https://telegra.ph/file/af1f132e9aaa45fe08c3c.jpg", "https://telegra.ph/file/312006d79bd4be7929dd8.jpg", "https://telegra.ph/file/043334fa625a1802693d1.jpg"]}

**Comment by kongicus** [comment]
山本郡八峰町，在海滨，是个小镇。从秋田站坐电车去这里要2小时，开车一个半小时。
这个地方比较出名的是每年8月1日在白瀑神社举行“神轿沐浴”，有个17米高瀑布的自然景点，不是特别小的瀑布，去过的人评价都还蛮好的。
还有个年轻人约会喜欢去的千石角，有个小灯塔，有天涯海角的浪漫氛围。
钓鱼爱好者的话，这里有个叫真瀬渓谷三十釜的地方，真瀬的浅滩溪钓比较有名。

看REINS上成交价记录的话，1988这个年份，这个价格虽然不算太高，但应该还可以再砍点。
