### ISSUE TITLE
2023-10-20: 岡山市南区迫川

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#32]
{"original_url": "https://www.athome.co.jp/kodate/6979845119/", "price": 9000000, "location": [133.8756982, 34.5354185], "address": "岡山市南区迫川", "rooms": "6LDK", "land_area": 310.79, "floor_area": 159.12, "completed_date": "1981-01", "city": "岡山県岡山市南区", "description": "広々とした延床面積１５９．１２㎡の居室空間、更に新しい趣味を見つけてみたくなる庭のある住まいが暮らしにスペースと心にゆとりをつくります。", "photos": ["https://telegra.ph/file/ff44b701fdb4c7d8440f1.jpg", "https://telegra.ph/file/4c619f3b117f6c81a3e9d.jpg", "https://telegra.ph/file/024712c83c61211296453.jpg", "https://telegra.ph/file/85a1f3b9ffd70aef23b84.jpg", "https://telegra.ph/file/d7bf57a52d426732806ba.jpg", "https://telegra.ph/file/b42ee9b64d583e6a49a53.jpg", "https://telegra.ph/file/5dac220a53708ee0e1013.jpg", "https://telegra.ph/file/fa39e7f9c20948ae12d10.jpg", "https://telegra.ph/file/9e351ec359f441dcf6774.jpg", "https://telegra.ph/file/223cf4cb19158f7e50c35.jpg", "https://telegra.ph/file/aa4b3555fab8b70d97dc3.jpg", "https://telegra.ph/file/2ca91f4d3913d4ea0be01.jpg", "https://telegra.ph/file/b29ea49f6b827a5dbac62.jpg", "https://telegra.ph/file/e060a6fcbbb68a2b80f36.jpg", "https://telegra.ph/file/6e7e5573569f87c33d0f7.jpg", "https://telegra.ph/file/057b9a02b453c8591d2e1.jpg"]}

**Comment by kongicus** [comment]
从冈山市市区开车去这里大概半小时，离迫川站走路3分钟。
传统日式建筑，冈山市南边的镇上，里面的装修是上个世纪那款，可以停3个车，带田。
这个价格，同地段一样离车站走路3分钟的新建分让一户建，100平建物145平土地，新的是1980万。

查了下迫川公示地价两万四千五一平
所以这个地段这个新建的分让一户建，地皮价是 145平x 24500円/平=355.25万円，就是17万多人民币。修房子的材料和工费是1980万 - 355.25万=1624.75万円，就是79万人民币，建卖的话有点贵。

乘一下这块二手房子的地的面积，310.79平 x 24500万円，这个地皮应该是761万。
用这个老房挂的900万，减这个根据公示地价算出来的地皮价761万，地面建筑物残值房主认为是900-761=139万円。

顺便这个外墙看图是黑的木板，猜是烧杉工艺的外墙。
烧杉是古代的外墙工艺，把杉板表面烧出碳化层贴在外墙上，所以看起来是黑的。古代因为没现代科技，只能用这个碳化层来加强抗腐蚀、抗虫蛀之类的性能，但现代用这个工艺好处主要是风情管够，毕竟纯为了耐用的话该直接用镀锌钢板外墙啊
