### ISSUE TITLE
2023-10-20: 安芸高田市美土里町本郷

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#33]
{"original_url": "https://www.athome.co.jp/kodate/6980046696/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 11500000, "location": [132.6108600669579, 34.71600580060712], "address": "安芸高田市美土里町本郷", "rooms": "4DK", "land_area": 533.5, "floor_area": 116.65, "completed_date": "2003-01", "city": "広島県安芸高田市", "description": "■平屋暮らしのセカンドハウス！□建築後ほぼ未入居の本格木造平屋建！■田舎物件の為、不便ですが自然豊かなロケーション良好な場所です！□神楽門前湯治村まで車で約７分の場所です！", "photos": ["https://telegra.ph/file/424feff93ac8f02ddb1c1.jpg", "https://telegra.ph/file/fbc72c455b80983e9fe75.jpg", "https://telegra.ph/file/f34948c2419f247254dd6.jpg", "https://telegra.ph/file/0f4c14b6d48907a25c3ec.jpg", "https://telegra.ph/file/e2fdd69200e1764c59bb5.jpg", "https://telegra.ph/file/23127574201e1d8f50fba.jpg", "https://telegra.ph/file/acaf259b9dda9c54680e9.jpg", "https://telegra.ph/file/75ba9c1670948d6772893.jpg", "https://telegra.ph/file/4d67000f5dc0dbf1c4487.jpg", "https://telegra.ph/file/cc18c936d52c1b44622bf.jpg", "https://telegra.ph/file/586dd078bf78956700b77.jpg", "https://telegra.ph/file/d4a434d6fc5ea8b02c969.jpg", "https://telegra.ph/file/149fb974ecdcdb8f281e7.jpg", "https://telegra.ph/file/c138fd6cc1094813ea4c5.jpg", "https://telegra.ph/file/15ba73992c27686938690.jpg", "https://telegra.ph/file/83f0c20d4bf8f60b6930e.jpg", "https://telegra.ph/file/e67522fbc906e194cf4c1.jpg", "https://telegra.ph/file/a6bbd9a8ac4036bdcce18.jpg", "https://telegra.ph/file/7163930cdef1d21289069.jpg", "https://telegra.ph/file/38b8732f2a65b0edc59c1.jpg", "https://telegra.ph/file/76b5dcf8984a5b99c16de.jpg"]}

**Comment by kongicus** [comment]
开车去广岛市市区1个小时，基本上没有公共交通
去年11月换过灶和热水器，今年5月重修过化粪池
装修是这个世纪的风格，室内属于干干净净可以直接住进去的水准

这个地方开车7分钟可以到一个度假村“神楽門前湯治村，是一个当地打造的几个店连起来的乡土度假风情街。

这个地方3885円/m2
这片地的面积533.5m²，地皮价533.5 x 3885 =2072647.5円，207万円折人民币大约10万1千。

这个物件挂牌1150万，
也就是房东认为地面建筑物值1150-207=943万円，大约45万人民币。其实个人感觉这个价高了，还能砍。

看下这个市的新筑的行情，215平地，建物91平，卖1880万。也就是扣掉地价215m²x3885円/m2=835275円，扣掉83万円的地价，建材和工费是1880万卖价-83万地价=1797万，大约87万人民币。

所以这个老房子和新建的比，地面建筑物过了20年，折价折掉一半。
