### ISSUE TITLE
2023-10-22: 松阪市飯南町粥見

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#34]
{"original_url": "https://www.athome.co.jp/u?s=7cJfXMD", "price": 11800000, "location": [136.3905369, 34.4522873], "address": "松阪市飯南町粥見", "rooms": "4DK", "land_area": 959.55, "floor_area": 130.83, "completed_date": "2007-05", "city": "三重県松阪市", "description": "農地付き　美邸平家建て　南面農地の為日当たり良好　別棟倉庫７９．４９㎡有り", "photos": ["https://telegra.ph/file/8e78d4dd7d3cf7965183f.jpg", "https://telegra.ph/file/ed73b76c97149a4c3f7c2.jpg", "https://telegra.ph/file/c4da3734026dbb6d5d8cf.jpg", "https://telegra.ph/file/89d3ed3802d7467606146.jpg", "https://telegra.ph/file/07e7f8c2ebc0f15423984.jpg", "https://telegra.ph/file/3d2607e8fbcb6ee7ccb34.jpg", "https://telegra.ph/file/71b67dc9749f4af364368.jpg", "https://telegra.ph/file/7bdb9ac0172f6648d12f0.jpg", "https://telegra.ph/file/2a55f8c0d951a124e7ee2.jpg", "https://telegra.ph/file/3422907b5cd5dabc09523.jpg", "https://telegra.ph/file/05e78576b220b8358ce36.jpg", "https://telegra.ph/file/dbbbca7b56f49c7cba05c.jpg", "https://telegra.ph/file/a934dadcc747927f8b0f7.jpg", "https://telegra.ph/file/2b3451df051a5ad775bae.jpg"]}

**Comment by kongicus** [comment]
2007年新修的看起来比较新，现在没人住在里面。
因为在村里地大，有车库，车库里面看图里面放了农机，屋主可能是务农的吧
周围也不是说啥生活设施也没有，还是有个Mrs.SMART中型超市。
开车去松阪市区要40分钟。这个房子走2分钟有个火车站，坐车去松阪市中心50分钟，票价1000日元。

说起松阪的话，当然是日本顶级和牛松阪。
