### ISSUE TITLE
2023-10-23: 富士市松岡

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#35]
{"original_url": "https://www.athome.co.jp/kodate/6979537419/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 14300000, "location": [138.64221007301634, 35.15072298504619], "address": "富士市松岡", "rooms": "5LDK", "land_area": 170.0, "floor_area": 147.55, "completed_date": "1982-01", "city": "静岡県富士市", "description": "利便性もよく閑静な住宅街。", "photos": ["https://telegra.ph/file/75abf43af19e411bfce72.jpg", "https://telegra.ph/file/69c5a1d37ed11eb517228.jpg", "https://telegra.ph/file/b5f4dc502af4634747c8d.jpg", "https://telegra.ph/file/3da7eea18fc8bd4862a37.jpg", "https://telegra.ph/file/3277407b57d2ac9934f05.jpg", "https://telegra.ph/file/9cc09ff23e6ecd8d196a8.jpg", "https://telegra.ph/file/0c629537e5a2625232bd6.jpg", "https://telegra.ph/file/a42c815f57f29ebf2ad4c.jpg", "https://telegra.ph/file/4069085a269f5b15ec488.jpg", "https://telegra.ph/file/263c0a8fd127067059d29.jpg"]}

**Comment by kongicus** [comment]
在富士市市区里，走路去JR富士站或者JR柚木站都是15分钟左右。两边都有路的角地，采光很好。
2018年翻新过，里面看起来很新，地图街景上去年2022年还住着人，停了两个小汽车和一个自行车，不是空置很多年的。房子算是日本房子里大的5LDK，户型比较好。

富士市因为有富士山下来的水，所以水资源丰富，很多很多年前富士市因为王子造纸啥的几个大的造纸工厂在这里，污染比较大，但2012年之后这里的造纸厂全部都关了。
在富士市里面往北看就是富士山，这里做旅游的很多，不做纸了就是旅游了。
