### ISSUE TITLE
2023-10-24: 飛騨市古川町中野

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#38]
{"original_url": "https://www.athome.co.jp/kodate/6974057624/?DOWN=1&BKLISTID=001LPC&sref=list_picture", "price": 9000000, "location": [137.1596126, 36.2444895], "address": "飛騨市古川町中野", "rooms": "9SLDK", "land_area": 981.71, "floor_area": 259.19, "completed_date": "1974-06", "city": "岐阜県飛騨市", "description": null, "photos": ["https://telegra.ph/file/8cea28aff43a6b3eea847.jpg", "https://telegra.ph/file/e1f79df4922fe69515cde.jpg", "https://telegra.ph/file/18ddc3edb08f9f528b10b.jpg", "https://telegra.ph/file/108e50e6e029f77f0a67b.jpg", "https://telegra.ph/file/5aedcb535f4eb100873a5.jpg", "https://telegra.ph/file/c5fe238810dd4a01c0af8.jpg", "https://telegra.ph/file/a58213f3860a4b40732b4.jpg", "https://telegra.ph/file/2012d5854cb53bc82383c.jpg", "https://telegra.ph/file/2a93df5e795ae27cb10d5.jpg", "https://telegra.ph/file/d53996bc6530bb3683cae.jpg", "https://telegra.ph/file/8df4232067e9b0a486ae6.jpg", "https://telegra.ph/file/a8320b425ec999867ec45.jpg", "https://telegra.ph/file/8336c0937f5794910730b.jpg", "https://telegra.ph/file/83dd0f4bb08f5871f97d2.jpg", "https://telegra.ph/file/e796def600ebd5a412d72.jpg", "https://telegra.ph/file/dc4bf75eff0d8b44ee69c.jpg", "https://telegra.ph/file/bc81bcad3eb8ba45793f5.jpg"]}

**Comment by kongicus** [comment]
走路去最近的杉崎站走路20分钟，这个房子旁边有一家古民家咖啡馆。
飛騨的旅游最近还挺火的，这个房子所在的杉崎御所樱夜景很出名。
