### ISSUE TITLE
2023-11-02: 羽生市大字羽生

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#44]
{"original_url": "https://www.athome.co.jp/kodate/1026740780/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 7800000, "location": null, "address": "羽生市大字羽生", "rooms": "4DK", "land_area": 117.92, "floor_area": 107.85, "completed_date": "1985-01", "city": "埼玉県羽生市", "description": null, "photos": ["https://telegra.ph/file/5151b3ef8dac7f61ab370.jpg", "https://telegra.ph/file/d6d00c2f45f849836e54e.jpg", "https://telegra.ph/file/df5354913da431f617d69.jpg", "https://telegra.ph/file/361b6afa616ce1fa86467.jpg", "https://telegra.ph/file/72b97f4bd147f9cc53ffc.jpg", "https://telegra.ph/file/4ffffe17f6ee8da847f83.jpg", "https://telegra.ph/file/8ffa0db1740b7ca6eea8d.jpg", "https://telegra.ph/file/a6b0e187d0647779dfc8e.jpg", "https://telegra.ph/file/f791fe124a300fe8b282a.jpg", "https://telegra.ph/file/8c56ed1d8301029c962fc.jpg", "https://telegra.ph/file/a3adfdf2dbe665dab6916.jpg", "https://telegra.ph/file/ca194c48d29604d924c7e.jpg", "https://telegra.ph/file/3723f6e94153965a60a59.jpg", "https://telegra.ph/file/ea9508495226963ab769b.jpg", "https://telegra.ph/file/97b7881739cf2cde5d62d.jpg", "https://telegra.ph/file/39713c2ad7bf691c2ea59.jpg", "https://telegra.ph/file/b5699873bcc250ecba87a.jpg", "https://telegra.ph/file/a67e54206836623f588b0.jpg", "https://telegra.ph/file/a0e8b6663ea760c953bd9.jpg", "https://telegra.ph/file/e9e6782f97bd34d2cfc89.jpg", "https://telegra.ph/file/65d4b893f2df55bebd82e.jpg", "https://telegra.ph/file/bf9ec951163d74d0235db.jpg", "https://telegra.ph/file/39d5b553be8d9e037c5a1.jpg", "https://telegra.ph/file/819b013e184206eecf25c.jpg", "https://telegra.ph/file/c26fa25eec27c7ad56109.jpg", "https://telegra.ph/file/fb90ad9213d1e02002700.jpg", "https://telegra.ph/file/3297129461c42b93cd45b.jpg", "https://telegra.ph/file/5a3f9b34e91f334b96891.jpg"]}

**Comment by kongicus** [comment]
离最近的车站走路2分钟，从这里到东京中心坐电车1小时40分钟，开车1小时。

乡下小镇，新筑2500万，这个780万确实算便宜了，但看了下事故网站暂时没看到啥异常。
