### ISSUE TITLE
2023-11-07: 出雲市国富町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#46]
{"original_url": "https://www.athome.co.jp/kodate/1011071977/", "price": 8900000, "location": null, "address": "出雲市国富町", "rooms": "6DK", "land_area": 805.51, "floor_area": 343.82, "completed_date": "1919-01", "city": "島根県出雲市", "description": null, "photos": ["https://telegra.ph/file/f74eb55c06b18bc7d2077.jpg", "https://telegra.ph/file/3816a84da0d168a520276.jpg", "https://telegra.ph/file/62422cc1f4cf14d9de9a3.jpg", "https://telegra.ph/file/5bea262f74beb02590213.jpg", "https://telegra.ph/file/dbb7b8827825be7a1d757.jpg", "https://telegra.ph/file/3ca8a3444c85ddd7f76b7.jpg", "https://telegra.ph/file/496cc1b2dc7924708b803.jpg", "https://telegra.ph/file/85bdfd493f54e09daf2c2.jpg", "https://telegra.ph/file/11d65e91d53410dd0ec80.jpg", "https://telegra.ph/file/b8c0b4ef57307fe1e4307.jpg", "https://telegra.ph/file/ff93651a419c138c5fc0b.jpg", "https://telegra.ph/file/7f9babb7c7a876dcd64c4.jpg", "https://telegra.ph/file/0068c4687de66c1574f8f.jpg", "https://telegra.ph/file/16e1379ad00c40a945072.jpg", "https://telegra.ph/file/fbad00c1f917c75237386.jpg", "https://telegra.ph/file/803202dc447f59fbf1a37.jpg", "https://telegra.ph/file/1aefd4103a4a6b3832f30.jpg", "https://telegra.ph/file/87494dd33c19e75ca21fe.jpg"]}

**Comment by kongicus** [comment]
这栋是1919年建的，受文化财保护法的限制，里面留存东西不能随便改。但里面还是有个上个世纪风格的厨卫，改建应该还是能改建，属于古民居改建范畴的事了。
	
这个房在旅伏站走路12分钟的地方，西边是旅伏山，旅伏在出云市区的北边，离出云市中心开车12分钟，也不算深山老林，算镇上。
	
这种房子的存在说明这里的土地和建筑物是能做到有百年延续性的[偷笑R]
