### ISSUE TITLE
2023-11-11: 熊本市北区植木町岩野

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#49]
{"original_url": "https://www.athome.co.jp/kodate/6979227076/", "price": 12800000, "location": [130.6979377, 32.9039657], "address": "熊本市北区植木町岩野", "rooms": "4DK", "land_area": 240.75, "floor_area": 115.13, "completed_date": "1999-12", "city": "熊本県熊本市北区", "description": "山東小　五霊中校区　Ｐ２台　植木病院徒歩４分", "photos": ["https://telegra.ph/file/f728eb0b9492ece3ca830.jpg", "https://telegra.ph/file/884cd64c87dd033851299.jpg", "https://telegra.ph/file/eb153add0b91d76f15949.jpg", "https://telegra.ph/file/e1e6757c3b2508396aa0b.jpg", "https://telegra.ph/file/0bb40658a407c4ffeb18c.jpg", "https://telegra.ph/file/73371c4f663a338903293.jpg", "https://telegra.ph/file/10aead37631364b91ad40.jpg", "https://telegra.ph/file/dbd87a21660d1b64ff5aa.jpg", "https://telegra.ph/file/5f534fb0a0fa1218dca83.jpg", "https://telegra.ph/file/fb22f3b36bfa7e60b3f34.jpg", "https://telegra.ph/file/4dcd4737cd8df3063bef3.jpg"]}

**Comment by kongicus** [comment]
这栋在熊本，但是在熊本北区，算镇上，这个能这么便宜，大概因为是墓景房。
和坟墓中间隔了一块地，这块间隔里面种了很多植物挡视线，但可能距离近吧，旁边有嫌悪施設，所以能这么便宜。
1999年修的不算太老，旁边走四五分钟有市立医院和体育馆、公园，去附近的超市走路11分钟。
熊本的房子整体还是涨了点，从富士康说要去设厂，但厂子在机场那边，这里完全不在厂子那边。说起富士康厂JR豊肥本線的肥後大津站那边，新筑三千万，新一点的二手两千多万（这十多二十年修的），八几年的二手能挂到一千五百万左右，也是没想到能这样玩

**Comment by kongicus** [comment]
这栋在熊本，但是在熊本北区，算镇上，这个能这么便宜，大概因为是墓景房。
和坟墓中间隔了一块地，这块间隔里面种了很多植物挡视线，但可能距离近吧，旁边有嫌悪施設，所以能这么便宜。
1999年修的不算太老，旁边走四五分钟有市立医院和体育馆、公园，去附近的超市走路11分钟。
熊本的房子整体还是涨了点，从富士康说要去设厂，但厂子在机场那边，这里完全不在厂子那边。说起台积电厂JR豊肥本線的肥後大津站那边，新筑三千万，新一点的二手两千多万（这十多二十年修的），八几年的二手能挂到一千五百万左右，也是没想到能这样玩
