### ISSUE TITLE
2023-11-13: 前橋市粕川町新屋

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#50]
{"original_url": "https://www.athome.co.jp/kodate/1004508780/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 13800000, "location": null, "address": "前橋市粕川町新屋", "rooms": "4LDK", "land_area": 286.73, "floor_area": 105.16, "completed_date": "2004-11", "city": "群馬県前橋市", "description": "【ソルホーム】11/13更新＼11月のご成約プレゼントキャンペーン実施中／ ◆本日のご案内も大歓迎です♪◆条件に合った他物件も同時ご紹介可能です！ まずはお気軽にお問い合わせを♪", "photos": ["https://telegra.ph/file/686c5bf13705029fee102.jpg", "https://telegra.ph/file/6a0a954ed084eaad9046c.jpg", "https://telegra.ph/file/6728a40c308433d400a3e.jpg", "https://telegra.ph/file/8bdd3d4718bbd7ef75ccb.jpg", "https://telegra.ph/file/bfd22fbdd95ac4bf12838.jpg", "https://telegra.ph/file/426e5dcb98ed809af160c.jpg", "https://telegra.ph/file/07d1e2fbf1a5d32652d0e.jpg", "https://telegra.ph/file/9c2be4d80202d21a78368.jpg", "https://telegra.ph/file/af728e94c5226875a12f3.jpg", "https://telegra.ph/file/63e3b681eef3ada055ccb.jpg", "https://telegra.ph/file/6db594d33afe4fd70abf5.jpg", "https://telegra.ph/file/5327aff24e1b77367532c.jpg"]}

**Comment by kongicus** [comment]
不算太老，去年翻新过，还是在镇上，不算太村的地方。但是有点奇怪的是，去年10月就翻新了，为什么现在还在卖……难道一年都没卖出去吗。粕川町现在基本没有新的修好的现房卖，基本上现在挂出来的二手一户建的最低价。但如果是2013年修的有一栋，就只比这个贵两百多万。
这个地方土地价格公示地价现在是一平17866日元，这个地286.73平的话，地按公示地价是512万日元。这种木造的修这么多年了，感觉挂得有点高啊，这个如果一直没卖出去，估计再砍个两百万差不多。

顺便一提一个和这个房子没关系的，看这一片粕川町新屋站的房子的时候，去大岛teru看了下，新屋站车站走一两分钟远有个地标记了老人孤独死，现在那块地全部拆掉铲平了又在卖，有的人在意，有的人可能不在意。孤独死没有告知义务，但是如果是很久之后才发现进行了特殊清扫是有告知义务的，但这样就有一些模糊的边界，很久之后发现的久怎么界定，还有一些故意隐瞒的……所以在意的人还是买之前调查一下……
