### ISSUE TITLE
2023-11-20: 流山市大字東深井

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#57]
{"original_url": "https://www.athome.co.jp/kodate/6980116841/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 22800000, "location": null, "address": "流山市大字東深井", "rooms": "5LDK", "land_area": 171.04, "floor_area": 145.0, "completed_date": "1990-03", "city": "千葉県流山市", "description": "◇東武野田線運河駅までわずか２３０ｍ徒歩３分の好立地◇南向き陽当り良好！大量洗濯物も安心◇広々５ＬＤＫリフォーム自由◇人気の流山エリアで５０坪超え◇流山街道すぐお車でおおたかの森までアクセス良", "photos": ["https://telegra.ph/file/2e95cf5d86a503c7a0f93.jpg", "https://telegra.ph/file/b2eef4823eca8a87fa4f8.jpg", "https://telegra.ph/file/aa8e74bf7f9c26b302be5.jpg", "https://telegra.ph/file/4e82ef9668923982f7f0e.jpg", "https://telegra.ph/file/a04a5de982b8b137b6db0.jpg", "https://telegra.ph/file/9e62dea84177dae12a14a.jpg", "https://telegra.ph/file/9351aacce5d481f841686.jpg", "https://telegra.ph/file/819442ca0cbc2e2f1c74d.jpg", "https://telegra.ph/file/da28fab7682d583e529cc.jpg", "https://telegra.ph/file/c8a00c9d0ea1d2e310508.jpg", "https://telegra.ph/file/7946752854759d10653ef.jpg", "https://telegra.ph/file/8aabe836514bede4684e3.jpg", "https://telegra.ph/file/40b161a136247a520c0c6.jpg", "https://telegra.ph/file/b78cde5a0e45130dab47c.jpg"]}

**Comment by kongicus** [comment]
千叶流山市的一栋，很大，建筑面积有145平，土地171平，1990年修的，离车站运河站走路3分钟，去东京都心坐电车，奢侈点坐特急加钱50分钟，坐一般的60分钟。这种条件的一般3500万开外吧，4000也不奇怪啊，但这个2280万还那么大，明显比市场价低。

看了下运河站附近的地图，离车站这么近的有一栋二手是5000多万，而且一百平，我也觉得这么便宜的是不是有诈啊……然后去大岛看了下，把车站附近的看了下，也没这栋。
离车站远一点的话，有一栋两千六百万，但也没这个145平这么大啊……而且这栋也不是再建不可，是角地，里面住户也搬出去了没人住，看起来表面没什么重大的缺陷。

硬要说怪的地方的话，挂牌这栋出来的中介是个福冈的中介，不是关东的中介，而且这家只挂了这一栋。
