### ISSUE TITLE
2023-11-21: 鴻巣市箕田

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#59]
{"original_url": "https://www.athome.co.jp/kodate/1042561070/?DOWN=2&BKLISTID=002LPC&sref=list_simple", "price": 15800000, "location": null, "address": "鴻巣市箕田", "rooms": "5LDK", "land_area": 174.0, "floor_area": 187.13, "completed_date": "1996-03", "city": "埼玉県鴻巣市", "description": "●2世帯住宅（玄関２か所）。分離しています。大変綺麗にお使いです。●収納豊富、陽当たり良好●車３台駐車可能　●JR高崎線「北鴻巣」駅徒歩１２分。　●本物件は、容積率をオーバーしております。", "photos": ["https://telegra.ph/file/a8f3c0366755abb9187e5.jpg", "https://telegra.ph/file/7b9802f7472a3486887e7.jpg", "https://telegra.ph/file/0069b8eaada0c8caf8a79.jpg", "https://telegra.ph/file/75f5dfae48b9627dc9c44.jpg", "https://telegra.ph/file/30eeca770262268256bc0.jpg", "https://telegra.ph/file/d59b17f6cd16c4dedd2c6.jpg", "https://telegra.ph/file/f7211598c1f69b0ff1225.jpg", "https://telegra.ph/file/dc71c41a14ad800b56240.jpg", "https://telegra.ph/file/11cf9870b9523827adb7f.jpg", "https://telegra.ph/file/b61f297e005bc44445eed.jpg", "https://telegra.ph/file/3a7d42a59b855bd843dbf.jpg", "https://telegra.ph/file/fb4cafd8c732b6b85ae76.jpg", "https://telegra.ph/file/1de6345c81094a8dc98cb.jpg", "https://telegra.ph/file/5fb77dc5a687c06a75f45.jpg", "https://telegra.ph/file/6fc740030e1b02e9190c6.jpg", "https://telegra.ph/file/7d570a9c62f57014460a3.jpg", "https://telegra.ph/file/3c6b4b9a68e53269fe9d7.jpg", "https://telegra.ph/file/5d5ee44d2b03b26ff7b7f.jpg", "https://telegra.ph/file/e4efad733249e35927a1a.jpg", "https://telegra.ph/file/5b6aee5731d67aca30d5d.jpg", "https://telegra.ph/file/22d69df59460f55fc6c48.jpg", "https://telegra.ph/file/42abce63557105fa9519f.jpg", "https://telegra.ph/file/013f7400340b7b0c71932.jpg", "https://telegra.ph/file/1bbb971a2c57ef9dd74a5.jpg", "https://telegra.ph/file/c23aaa45348ab9847f233.jpg", "https://telegra.ph/file/b43541c193bca77788e54.jpg", "https://telegra.ph/file/00318f42189b845efca6e.jpg", "https://telegra.ph/file/dfc0cde6d13697e54bc31.jpg", "https://telegra.ph/file/06d640b6926f55e1bbc27.jpg", "https://telegra.ph/file/5ea098755f8eb9c745923.jpg", "https://telegra.ph/file/8f6f08af6776a7e9c61fd.jpg", "https://telegra.ph/file/d105ee394f78ed4c7829c.jpg", "https://telegra.ph/file/215ee375a80b43a82542b.jpg", "https://telegra.ph/file/78883a8e0788d4a35f8e8.jpg", "https://telegra.ph/file/de0b38dff00710f6d5802.jpg", "https://telegra.ph/file/91e425b940aa17c19a0bd.jpg", "https://telegra.ph/file/2f87eb1cdded22c57c016.jpg"]}

**Comment by kongicus** [comment]
走12分钟到车站北鴻巣駅（但一般来说真正走的时间比中介给的这个时间长，估计自己真走到车站得15-18分钟），再刚好一个小时到东京都心东京站，一趟990日元。
它大啊，建筑面积有187平，土地174平，九六年修的，看里面内装原来房主保养得很好。但这个房子有个问题，给改成二世带住宅了，户型上有两个玄关，相当于给劈成两个房子，户型给改烂了。但也因为有改过户型吧，有一套厨卫是这个世纪的style，有一套厨卫是上个世纪的。这种确实……不太好卖吧。

北鴻巣车站附近九几年修的基本就这个价，1500万上下波动。
但是最近十年内左右修的，有好几个我觉得有点乱挂离谱了，给卖到三千二百万到三千八百万，离车站还走路50分钟这种……合着十年内的想当新筑卖。正常点的2019修的给挂到两千四百万，也有好几套都这样挂的，这个还算合理吧。
