### ISSUE TITLE
2023-10-09: 旭市後草

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#6]
{"original_url": "https://www.athome.co.jp/kodate/6979931245/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 29800000, "location": [140.6778558, 35.7294511], "address": "旭市後草", "rooms": "6SLDK", "land_area": 1.0, "floor_area": 218.2, "completed_date": "1993-02", "city": "千葉県旭市", "description": "総武本線「飯岡」駅から徒歩９分の広い戸建です！サンデッキ、２台駐車可能なガレージもございます。室内の内見も可能です。", "photos": ["https://telegra.ph/file/611376d25227c838d83a3.jpg", "https://telegra.ph/file/6cfdf27b5b8a333b337ec.jpg", "https://telegra.ph/file/5a958e20f051b84a7c54c.jpg", "https://telegra.ph/file/0ce6bebb386a73ba8e601.jpg", "https://telegra.ph/file/c3b116089bcc81d990ef7.jpg", "https://telegra.ph/file/84dc30b3ad9457d470ac9.jpg", "https://telegra.ph/file/8e8e93160bdc4e973dbc9.jpg", "https://telegra.ph/file/b503d768ab615ee560e20.jpg", "https://telegra.ph/file/2d16819ac472859509ce9.jpg", "https://telegra.ph/file/c7bf208a083cfea83e3b0.jpg", "https://telegra.ph/file/07e6e82fedf6f03e0ae13.jpg", "https://telegra.ph/file/9e056c6079fcc07f35cc9.jpg"]}

**Comment by kongicus** [comment]
这个房子离车站不远，很大，院子也很大。但是路对面是一片墓碑……因为在一个真言宗的寺庙在那边。
看地图的话，2012年这个房子卖过，后面肯定有人买了，把篱笆重新种上了绿植，还种了几种植物，绿植长了起来不怎么看得到路对面的墓碑了。

今年3月的时候还没在卖房状态，8月的街景又挂着卖了。几个月没卖出去，这个价肯定挂高了。

内装看起来可以直接住进去，不需要怎么再翻新。
离最近的小学走路10分钟，汽车3分钟；离最近的food center大超市骑自行车10分钟，开车5分钟。

这个地方在旭市的边上，离东京都心坐电车2小时，开车也2小时。

旭市在九十九里滨海岸线上，是一个与大海相伴而生的城市。这里海边上冲浪的人很多，也是农畜的一个大产地，育儿设施也不缺，千叶县内最大的综合医院也在旭市。
