### ISSUE TITLE
2023-11-22: 浜松市東区中野町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#60]
{"original_url": "https://www.athome.co.jp/kodate/6980506614/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 15800000, "location": [137.7936854, 34.7257451], "address": "浜松市東区中野町", "rooms": "5LDK", "land_area": 366.0, "floor_area": 167.68, "completed_date": "2002-03", "city": "静岡県浜松市東区", "description": "広々とした１１０坪の敷地に延床面積５０坪の居室空間☆気持ちにもゆとりを与える庭のある住まいが暮らしにスペースと心にゆとりをつくります。", "photos": ["https://telegra.ph/file/0d9fa0bbdc1ea1c54d5ed.jpg", "https://telegra.ph/file/00c88c71eb47c10e68b2e.jpg", "https://telegra.ph/file/943f6fbac75944e11d760.jpg", "https://telegra.ph/file/227439cad29af78b9deff.jpg", "https://telegra.ph/file/014ab95763c08437a0d25.jpg", "https://telegra.ph/file/ca0205798374bfbffffc5.jpg", "https://telegra.ph/file/89331842d8f9dbe6e7a97.jpg", "https://telegra.ph/file/2a08c9bfb53bcf3dd92c5.jpg", "https://telegra.ph/file/908e3a32f0c24455d8d31.jpg", "https://telegra.ph/file/eac67b5bc9bfb0e0d7aef.jpg", "https://telegra.ph/file/180e1251d22f891d79938.jpg", "https://telegra.ph/file/6d0a1ddff857a6765c7c4.jpg", "https://telegra.ph/file/635861795feb83d9999c0.jpg", "https://telegra.ph/file/711f632dd73f0065bdb3c.jpg", "https://telegra.ph/file/14230dce07742d0c16fda.jpg", "https://telegra.ph/file/304872a07315db129303f.jpg", "https://telegra.ph/file/3bc3ee604ce51a7e0661f.jpg"]}

**Comment by kongicus** [comment]
搜的时候眼前一亮，走路半小时到最近的JR天龙川站，1580万元，2002年修的，还167平这么大，土地366平，周围只有几户人，坐落在田里，但走几分钟过桥马上就是街区，生活设施齐全。但仔细一想，肯定事情不简单，不然不可能这么便宜的。
果然……是「許可宅地」。
浜松市有种叫“大规模既存集落”的概念，在都市计划法里这种土地不是市街化区域，是市街化调整区域，就是这个地方有山有水有田、有比较好的自然环境（在天龙川沿岸），所以一般是不让修新房子和改建之类的，一般是不让，但除非满足一些特定条件。
浜松这种土地挺多的，所以浜松的地和房子便宜是比较有名的……要再建增筑改建之类的话，具体条件在浜松的官网上，看了下对申请者、土地、建筑物等等都有要求。虽然对于住在那里的人来说，长住的话，满足条件也不难，但是就是有限制，麻烦。

一般现在修个新房子，一百平的，哪怕在小城市，一套弄下来怎么也要三千多万日元吧，浜松的新房，9月完工的，也差不多3200左右，贵的给卖到3800万4000万日元，但这种价格还是偏高了吧
浜松今年6月修的新房，在市区里面，不是乡下或者城乡结合部，浜北区，6月修的一直卖不出去已经降到2900万了，也不是什么特殊用地类型，也不是旗杆地之类的。
有点好笑的是，浜松不少去年2022秋季修好的一户建，当时可能成本猛涨了一波吧，一直不降价妥协还挂在3500万日元，甚至有些还挂原价4000多万。去年秋季修的，有个别挂2300万都卖不掉的，不知道这些为啥还能挂这么高，是成心不想卖了吧，或者是觉得总能骗到太信息不对称的冤大头
