### ISSUE TITLE
2023-11-23: 小田原市蓮正寺

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#61]
{"original_url": "https://www.athome.co.jp/kodate/1094131570/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 15800000, "location": null, "address": "小田原市蓮正寺", "rooms": "4LDK", "land_area": 113.37, "floor_area": 117.05, "completed_date": "2005-06", "city": "神奈川県小田原市", "description": "【小田原市蓮正寺戸建《４ＬＤＫ》】是非お気軽にお問い合わせください！", "photos": ["https://telegra.ph/file/169f2ee34f0e3d1b8dc92.jpg", "https://telegra.ph/file/e50cfdc400cd1659a357a.jpg", "https://telegra.ph/file/b29093cf5262edbe590b3.jpg", "https://telegra.ph/file/8b1a8a15fa391ae06bcae.jpg", "https://telegra.ph/file/71e40d4baec6b93ecd9ec.jpg", "https://telegra.ph/file/253758a5f2756eb95c9e3.jpg", "https://telegra.ph/file/0e740812356bdab6fed4f.jpg", "https://telegra.ph/file/4f84da8b5d9f823d703ab.jpg", "https://telegra.ph/file/641a1322c1df80ef1c9c4.jpg", "https://telegra.ph/file/3794a7567f745754b28b3.jpg", "https://telegra.ph/file/0458c38fa610087d79b5e.jpg", "https://telegra.ph/file/4009bbb232c8e2b426a55.jpg", "https://telegra.ph/file/8c8d091c17bae9098c3e6.jpg", "https://telegra.ph/file/7f4b9d43d06e9a1e99844.jpg", "https://telegra.ph/file/0af2b93380046173f4bb3.jpg", "https://telegra.ph/file/63597b61051c416f7c969.jpg", "https://telegra.ph/file/9521f102311c107add997.jpg", "https://telegra.ph/file/a86f606b58358a4fe8b2a.jpg", "https://telegra.ph/file/702891786fd2fbcdd8944.jpg", "https://telegra.ph/file/a9b963aa3717fd0b34995.jpg", "https://telegra.ph/file/531c052637732514dc2db.jpg", "https://telegra.ph/file/8974f5b5d3c07db4579d6.jpg"]}

**Comment by kongicus** [comment]
小田急小田原线莲正寺螢田駅走路10分钟（80米/分钟*10分钟=800米），117.05m²，1580万日元，角地，2005年修建，4LDK，一楼二楼各一个厕所。

螢田駅去东京都心东京站1个小时40分钟。

这个车站附近的一户建看了下能租12万一个月，一年144万，这个收益率这样单算的话……一年去到9%了。就算租便宜点，租10万，也有7%多。但前提是要能租出去，小地方倒也不一定能租出去。

这个价格算小田原市里很低的，一般小田原市零几年修的卖3000万左右，便宜点卖2800万，当然离车站特别近的，还有一个螢田駅走路5分钟的，但是175平，卖6590万。相比起来这个就太低了……这个房子10月中旬就挂出来了，现在还没卖掉，积水在卖都没卖掉。

要说表面上的缺陷的话……因为是角地，家的围墙外面紧贴个电线杆。但相比同地段的便宜得有点多，怀疑有诈，或者别的缺陷。

**Comment by kongicus** [comment]
小田急小田原线莲正寺螢田駅走路10分钟（80米/分钟*10分钟=800米），117.05m²，1580万日元，角地，2005年修建，4LDK，一楼二楼各一个厕所。

螢田駅去东京都心东京站1个小时40分钟。

这个车站附近的一户建看了下能租12万一个月，一年144万，这个收益率这样单算的话……一年去到9%了。就算租便宜点，租10万，也有7%多。但前提是要能租出去，小地方倒也不一定能租出去。

这个价格算小田原市里很低的，一般小田原市零几年修的卖3000万左右，便宜点卖2800万，当然离车站特别近的，还有一个螢田駅走路5分钟的，但是175平，卖6590万。相比起来这个就太低了……这个房子10月中旬就挂出来了，现在还没卖掉，积水在卖都没卖掉。

要说表面上的缺陷的话……因为是角地，家的围墙外面紧贴个电线杆。但相比同地段的便宜得有点多，怀疑有诈，或者别的缺陷。
