### ISSUE TITLE
2023-11-24: 足柄下郡箱根町芦之湯

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#62]
{"original_url": "https://www.athome.co.jp/u?s=7cCBn8D", "price": 13000000, "location": [139.04339411852416, 35.22394280568558], "address": "足柄下郡箱根町芦之湯", "rooms": "4LDK", "land_area": 881.0, "floor_area": 118.15, "completed_date": "1976-12", "city": "神奈川県箱根町", "description": "箱根芦之湯別荘地　ＬＤＫ１８帖　４ＬＤＫ　昭和レトロのおしゃれな別荘　敷地２６６坪で木々囲まれた安らぎの空間　箱根の山々を望む眺望", "photos": ["https://telegra.ph/file/c6f3061facc8e265846b4.jpg", "https://telegra.ph/file/d6222ee07ab2244c862f5.jpg", "https://telegra.ph/file/46171222e61387efabf1b.jpg", "https://telegra.ph/file/3bdd4a4b4eaa507ed7b16.jpg", "https://telegra.ph/file/9580aa034c5a75c8cd961.jpg", "https://telegra.ph/file/874f7c64ad4efc250a7b5.jpg", "https://telegra.ph/file/7adfa47f27a9655b72a72.jpg", "https://telegra.ph/file/cc0d8fd6b77c5007c9c81.jpg", "https://telegra.ph/file/575dfcb708df49f7d1bff.jpg", "https://telegra.ph/file/91483666329717053059b.jpg", "https://telegra.ph/file/e91d0b01285b27aa38f5f.jpg", "https://telegra.ph/file/10c591043ab7f9ea6a123.jpg", "https://telegra.ph/file/f374eef66b22d50e3d682.jpg"]}

**Comment by kongicus** [comment]
看看度假用的，土地881平，建物118.15平，1976年修的，1300万円，按现在汇率价格62万人民币。
这里开车去芦之湖边上游船码头那里要9分钟，4km多。去芦之湯那个温泉街走路8分钟，开车2分钟。这种现在的定位基本上还是卖给投资客了吧，日本现在度假的也不太像以前那样买个景区小别墅每年去住一两次，基本还是住店。
看看芦之湖周围的房子，这十多年修的小的，自己住家用的，基本上要3000外开外，卖4000万正常，这个卖得便宜，可能因为1976年修的，有点老了，或者有别的问题。
现在大的豪华一点的箱根别墅，卖七千万一亿的也有，这种确实房主不差钱挂着看缘分卖吧。
