### ISSUE TITLE
2023-11-25: 取手市宮和田

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#63]
{"original_url": "https://www.athome.co.jp/u?s=15nVq8D", "price": 20980000, "location": null, "address": "取手市宮和田", "rooms": "4LDK", "land_area": 146.59, "floor_area": 109.94, "completed_date": "2023-05", "city": "茨城県取手市", "description": "【限定1棟・本日ご見学可能物件】  ■藤代駅徒歩7分 ■吹抜リビング ■5LDK対応可  未公開写真はひだまりハウスHPにて公開中♪", "photos": ["https://telegra.ph/file/b9e2448a957b1fa5c7648.jpg", "https://telegra.ph/file/f81c30819058bff54bdd9.jpg", "https://telegra.ph/file/ed0b747594543d9bad2a7.jpg", "https://telegra.ph/file/f4d5004f521016d8ec6b0.jpg", "https://telegra.ph/file/f475c15d1cf610eb70598.jpg", "https://telegra.ph/file/9b051d9e08616e2144df3.jpg", "https://telegra.ph/file/decb5c1d38756c201a262.jpg", "https://telegra.ph/file/a1bc1dff99238963e3133.jpg", "https://telegra.ph/file/359e6386c07c3d07b361a.jpg", "https://telegra.ph/file/2e73f13dd8687471077cb.jpg", "https://telegra.ph/file/daf6d4f2592d340e79b0b.jpg", "https://telegra.ph/file/84f5a4a7705601ddb2f78.jpg", "https://telegra.ph/file/39488603873b4233a4fe1.jpg", "https://telegra.ph/file/a7aaf8f09aed66078354d.jpg", "https://telegra.ph/file/9b0951b7d330b85da29f9.jpg", "https://telegra.ph/file/b90df607d0e8546f1a42f.jpg", "https://telegra.ph/file/092bf9c447c6443e92811.jpg", "https://telegra.ph/file/596c141d59c6d289d4366.jpg", "https://telegra.ph/file/c1b635423a78b7e45b85d.jpg", "https://telegra.ph/file/5f5f9286cae9277a58506.jpg", "https://telegra.ph/file/fe773283b9712ca03a5cc.jpg", "https://telegra.ph/file/d50f3790da417295952b5.jpg", "https://telegra.ph/file/172ead6e381fc86a81f9c.jpg", "https://telegra.ph/file/e37d975a8ae24f358d1b1.jpg", "https://telegra.ph/file/023e39d89e22d5fe6200b.jpg", "https://telegra.ph/file/7fe07f246cbba0c61af67.jpg", "https://telegra.ph/file/c047eb096bece4f0b1bfd.jpg", "https://telegra.ph/file/a48f9145573e0239ed8a0.jpg", "https://telegra.ph/file/679ca5f9082840bd9c230.jpg", "https://telegra.ph/file/b4e9b3c5cee814d8525d0.jpg", "https://telegra.ph/file/9c30a18df68e9b5de3227.jpg", "https://telegra.ph/file/9823f91f4785d800b60b1.jpg", "https://telegra.ph/file/1ed0c67d0d1879168a9c2.jpg", "https://telegra.ph/file/18d60e4a0e7a7f5794538.jpg", "https://telegra.ph/file/fa112aab25c60e0c575d3.jpg", "https://telegra.ph/file/8cdace09068b8dcafbf4a.jpg", "https://telegra.ph/file/cafae58a9d05692635105.jpg", "https://telegra.ph/file/58e42e015a082b4ff4093.jpg", "https://telegra.ph/file/2ae4d15e3d4c436987048.jpg", "https://telegra.ph/file/fecfaf2a1415dce0736f7.jpg"]}

**Comment by kongicus** [comment]
这个房子到车站藤代站走路7分钟，藤代站坐到东京都心东京站55分，相当于从这里去东京大概1个小时出头。

土地146.59平，建物109.94平，角地，今年5月修的新筑，2098万円为啥相对周围便宜？现在还没卖出去，不懂咋回事儿，表面没问题，里面有啥问题不知道。
离车站走路7分钟地段正常新筑是2900万日元左右，离车站走路13分钟这个距离大概是2500万日元左右，反正这个相对便宜。

算下租金收益。离车站走路7-13分钟比较新的一户建，大概2010年之后修的，一个月一栋能租9万，这样算基本上租金收益5.1%，但算上交易的各种中介费手续费，可能接近5%吧。但小地方很可能租不出去。

走路7分钟这个地段，1990年前后修的老房子，卖接近1400万。但是老房子的话，这个地方租金一栋70多平的租5万6万，资金收益率大概有6%~7%，前提要能租出去。当然这个没算翻新和大修的钱，如果碰上要翻新和大修，搞不好要多出几百万日元吧，这样和新筑的租金收益差不多。
