### ISSUE TITLE
2023-11-27: 柏市高柳

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#64]
{"original_url": "https://www.athome.co.jp/kodate/1029884682/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 23900000, "location": null, "address": "柏市高柳", "rooms": "3LDK", "land_area": 128.95, "floor_area": 103.5, "completed_date": "2010-03", "city": "千葉県柏市", "description": "◆閑静な住宅地の設備の充実した邸宅です♪◆約18帖の広々としたリビングで笑顔の家族団らんを！！◆駅・学校も徒歩圏内で通勤、通学も楽々ですね♪", "photos": ["https://telegra.ph/file/62f23d34ed7c813d44a12.jpg", "https://telegra.ph/file/c12664b103d5a99414140.jpg", "https://telegra.ph/file/a1bcc57cd3dd8a7e18d02.jpg", "https://telegra.ph/file/48c501ba4e85c659ff1a0.jpg", "https://telegra.ph/file/ec592f1ee1bc9ac38d0c0.jpg", "https://telegra.ph/file/8115f2801503b21fc374e.jpg", "https://telegra.ph/file/cd73d74858bdd7df593be.jpg", "https://telegra.ph/file/2850dba443b162bb3cf42.jpg", "https://telegra.ph/file/dc22c925cda23928e9cd1.jpg", "https://telegra.ph/file/f64b8703b997ce9236ee4.jpg", "https://telegra.ph/file/3b6b1f3816f32cd5d51e1.jpg", "https://telegra.ph/file/c1fb27753f095981a6aff.jpg", "https://telegra.ph/file/7a816a00c15e3260c7445.jpg", "https://telegra.ph/file/3d9fe98531e60fb8b2aa8.jpg", "https://telegra.ph/file/fa1bd38297d8db0379682.jpg", "https://telegra.ph/file/6afaa46e30a56f172a7b0.jpg", "https://telegra.ph/file/2ed6d14707aa211e3aae7.jpg", "https://telegra.ph/file/54edb822c7ad28478fc70.jpg", "https://telegra.ph/file/833075e9e668a2ff4f20f.jpg", "https://telegra.ph/file/f54ce22794996fb138864.jpg", "https://telegra.ph/file/03879398f612725f14dc9.jpg"]}

**Comment by kongicus** [comment]
这个建筑面积103平，土地128平，价格2390万日元（115万人民币），在柏的高柳。

一般柏的房子没这么便宜，但高柳站的都相对比平均价低一点，因为这个站只有东武野田线从这过，去哪里都要换乘，不太方便。比如从高柳站区东京站，要先坐东武野田线去船桥转总武线，要花50分钟。
高柳的二手房（一户建），2010年左右修的2500~2600万日元，这栋比较便宜不知道为啥给降到接近2400万元。
如果从高柳坐2站去新鎌ケ谷，从新鎌ケ谷换乘到东京，虽然距离上不会绕到船桥去转车那么远，但加上等车，可能时间更长，还有车费贵40%。
所以这个地方地段没那么好，房价也没那么贵。
虽然高柳也是柏，但是高柳都在柏的最南边了，离方便的常磐线远。
