### ISSUE TITLE
2023-11-29: 日高市大字高萩

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#65]
{"original_url": "https://www.athome.co.jp/kodate/6980546910/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 19800000, "location": null, "address": "日高市大字高萩", "rooms": "4SLDK", "land_area": 167.0, "floor_area": 129.0, "completed_date": "2003-01", "city": "埼玉県日高市", "description": "街区が整備され住環境良好な区画整理地内。広々とした６ｍ道路に面した南西角地に位置しており開放感と陽当たりを備えています。車椅子生活の方にも配慮されたバリアフリー仕様・メーターモジュール。", "photos": ["https://telegra.ph/file/4c3ee728220095ab99c48.jpg", "https://telegra.ph/file/76cc25cfcddf55cf1e0b2.jpg", "https://telegra.ph/file/c1e98b70022ef13d3f8bd.jpg", "https://telegra.ph/file/5c8627be18a06d2cc9efe.jpg", "https://telegra.ph/file/e36702b15b76f1fddb1ff.jpg", "https://telegra.ph/file/66f71ea1093e330d1eda6.jpg", "https://telegra.ph/file/9c73c041981815d76f593.jpg", "https://telegra.ph/file/55df8fd94fa6578593c73.jpg", "https://telegra.ph/file/af82eab6c503380fc99c8.jpg", "https://telegra.ph/file/ecf968259952b8bccda07.jpg", "https://telegra.ph/file/a842ea2a6be2eecf48c47.jpg", "https://telegra.ph/file/a4858611a9db3b9674f92.jpg", "https://telegra.ph/file/ed2f3b4fcf47811f6af8a.jpg", "https://telegra.ph/file/5bfcbff0c89bcd7e497c1.jpg", "https://telegra.ph/file/605066ba281d5ecf68e52.jpg", "https://telegra.ph/file/b47d19cf9e3ad5c326310.jpg", "https://telegra.ph/file/328bd90211ba63018a583.jpg", "https://telegra.ph/file/b57d4fcae12d2b9457875.jpg", "https://telegra.ph/file/7cf064ab4abffe28a1af7.jpg", "https://telegra.ph/file/5ea1b5732d6de9de6a272.jpg", "https://telegra.ph/file/a1385414fe4ef82283e95.jpg", "https://telegra.ph/file/c1b1d6be743d851f22f6a.jpg", "https://telegra.ph/file/26e117030264f7fcf7d85.jpg", "https://telegra.ph/file/71ea6700a567ae0b768fb.jpg", "https://telegra.ph/file/9e03254eafa9921083178.jpg", "https://telegra.ph/file/9a4f1027f933afd5a5ec1.jpg", "https://telegra.ph/file/2a68b7709348a5339273f.jpg", "https://telegra.ph/file/271c8535376f13d23aed5.jpg", "https://telegra.ph/file/e8ca12c66393447fb1b77.jpg", "https://telegra.ph/file/b777edb5fa4b557e7c49c.jpg", "https://telegra.ph/file/160a81b9f9247c113d3b0.jpg", "https://telegra.ph/file/1c834f112290e533bdeae.jpg"]}

**Comment by kongicus** [comment]
角地，室内129平，土地167平，2003年修的，1980万，离武藏高萩站走路10分钟（按日本的80米1分钟算，离车站800米）。
埼玉大农村城乡结合部，差不多是镇上的感觉。去东京电车1h20min。
