### ISSUE TITLE
2023-12-05: 京都市南区上鳥羽八王神町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#69]
{"original_url": "https://www.athome.co.jp/u?s=18uwmxD", "price": 9800000, "location": null, "address": "京都市南区上鳥羽八王神町", "rooms": "3LDK", "land_area": 58.92, "floor_area": 110.06, "completed_date": "1989-11", "city": "京都府京都市南区", "description": "■近鉄「上鳥羽口駅」まで徒歩２２分■南東角地につき通風良好　前道幅員はゆったり約６ｍございます■軽自動車１台駐車スペース有（車種による）■福屋不動産販売　京都駅前店までお問い合わせくださいませ。", "photos": ["https://telegra.ph/file/08cfe143d6a9c3dea9d90.jpg", "https://telegra.ph/file/c290797f63963b49344e7.jpg", "https://telegra.ph/file/cd8270a4a3a86fda647f9.jpg", "https://telegra.ph/file/55ad3a3c6e1ed98b2196b.jpg", "https://telegra.ph/file/09970bf2e5ae74647a441.jpg", "https://telegra.ph/file/994b106ab7709f5bc6a83.jpg", "https://telegra.ph/file/0e6feeecba1a05f532121.jpg", "https://telegra.ph/file/0bf05f3e9d95365d3274d.jpg", "https://telegra.ph/file/e4260e3a4ab0401099d13.jpg", "https://telegra.ph/file/54bc78aca08a1e02a4d8f.jpg"]}

**Comment by kongicus** [comment]
建物110平，土地58平，不是旗杆地之类的，980万円（大约47万人民币），1989年修建。离电车站上鳥羽口駅徒步22分钟有点远，但是离京都南高速口那里很近。
京都少见的便宜房子，不是乡下。里面是啥样不知道，八九年修的还是有点老，还住着人，但这些感觉不是最大最大的问题吧。
最大的问题可能是这个房子有违法嫌疑，有告知事项。
本物件は建ぺい率・容積率を超過しております。这个房子建蔽率和容积率是超了规定的，可能有法律问题吧，估计要减建，这个麻烦了。
还有一个问题挺棘手，按现在这个设计，只能最多停一个轻车，如果不是轻车这个拿不出来车库证明。
这样的话……980万日元基本上算是买地了，房子没什么价值。
看了下这个地方的坪单价，这块土地58平（17.55坪），看了好几个数据，这个町算60万日元/坪吧，这样估算1000万日元左右。这个还要算拆除和改造的费用，综合算下来没有便宜太多，只能说是稍微比较便宜。
但这个比较好的是，这个不是长屋，左邻右舍没有和别人贴着，京都大阪那种完全和别人共用墙壁的长屋太多了，那种是真难搞。
