### ISSUE TITLE
2023-10-09: 大里郡寄居町大字用土

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#7]
{"original_url": "https://www.athome.co.jp/kodate/1086553874/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 7200000, "location": null, "address": "大里郡寄居町大字用土", "rooms": "5DK", "land_area": 139.98, "floor_area": 95.43, "completed_date": "1990-08", "city": "埼玉県寄居町", "description": "陽当たりもよく開放感もある角地です♪ お気軽にお問い合わせください♪", "photos": ["https://telegra.ph/file/e8c567acb9d1001960ec2.jpg", "https://telegra.ph/file/82df03a303ee65f2579da.jpg", "https://telegra.ph/file/356619d59ec4deec0c45c.jpg", "https://telegra.ph/file/c96cfcdbbb89003e4c784.jpg", "https://telegra.ph/file/c2dc6abd738ec88588f4f.jpg", "https://telegra.ph/file/840380d2326bfe7445294.jpg", "https://telegra.ph/file/b5e97ee0b83e6d689433d.jpg", "https://telegra.ph/file/2c072f0e9bfbc844fac22.jpg", "https://telegra.ph/file/07f0899ec3f3777defa8c.jpg", "https://telegra.ph/file/d3e3097d453d5aa515e46.jpg", "https://telegra.ph/file/a5294c3c0b50460d3064d.jpg", "https://telegra.ph/file/64142718f76b29b05ed75.jpg", "https://telegra.ph/file/dc116dcb2113df99e768a.jpg", "https://telegra.ph/file/be220618a4d9784182a69.jpg", "https://telegra.ph/file/5a3402f1a1378ce0e473c.jpg", "https://telegra.ph/file/1cb70c91e32fec128b690.jpg", "https://telegra.ph/file/6947660c5864acf5ec9b6.jpg", "https://telegra.ph/file/be5d77aaa12dd2599184b.jpg", "https://telegra.ph/file/91071259afabbf6ea59fa.jpg", "https://telegra.ph/file/81f4e7659b49427ac6484.jpg", "https://telegra.ph/file/29548f06c33bd8137522c.jpg", "https://telegra.ph/file/cedb3f2bad6e41fd13986.jpg", "https://telegra.ph/file/ffb3069b4fc0148dbaeb1.jpg", "https://telegra.ph/file/11cba1127bdd4edadad2a.jpg", "https://telegra.ph/file/f4f7d912e567823455c30.jpg", "https://telegra.ph/file/7f74487cf9bd82e4ce06d.jpg", "https://telegra.ph/file/4f4a0b95310acb77306e8.jpg", "https://telegra.ph/file/dfcc33769e8d1d40439b2.jpg", "https://telegra.ph/file/df5720336d947ee5202e6.jpg", "https://telegra.ph/file/73606900c7cca71733344.jpg", "https://telegra.ph/file/687d59d28187447d1b501.jpg", "https://telegra.ph/file/11fcca2cffd0e5097ac63.jpg", "https://telegra.ph/file/e6cc43b0c9011e149bef7.jpg", "https://telegra.ph/file/c7bd8008671be6e13138f.jpg", "https://telegra.ph/file/cc41045aeb4c7bce8948b.jpg", "https://telegra.ph/file/b9a82afe2e0bddcf09781.jpg", "https://telegra.ph/file/7ac272157462c659b3b79.jpg", "https://telegra.ph/file/1756ce42758f23b8ffa84.jpg"]}

**Comment by kongicus** [comment]
离车站很近走路3分钟，但是用土已经都快要到群马那边了，去高崎和前桥比去川越啥的更近。
坐电车和开车去高崎都差不多40分钟30km，去东京电车和开车都大概2小时100km。
外墙2020年翻新过，卫浴2021年翻新。乡下这个价还行吧，不算太贵，估计还能砍价。

如果住在用土的话，周围度假休闲的最近的是秩父吧，那边有些温泉之类的，但是开车去秩父那边也要40多分钟，或者还可以再多开半小时直接一脚油门去轻井泽玩，或者往北去群马的榛名山赤城山玩。
