### ISSUE TITLE
2023-12-08: 南魚沼市六日町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#70]
{"original_url": "https://www.athome.co.jp/u?s=7cOwLXD", "price": 9800000, "location": [138.8724859, 37.06696060000001], "address": "南魚沼市六日町", "rooms": "9LDK", "land_area": 306.0, "floor_area": 317.09, "completed_date": "1986-07", "city": "新潟県南魚沼市", "description": "六日町駅西口より徒歩６分、コンビニ、通学などさまざまな面で利便性の高い立地です。屋根雪自然落下、消雪用井戸あり。温泉あり。", "photos": ["https://telegra.ph/file/e8e5799c1a0418595c700.jpg", "https://telegra.ph/file/c9971d74714ca28002408.jpg", "https://telegra.ph/file/c71d0e62670da870e1276.jpg", "https://telegra.ph/file/105f3d18018bf5126d85b.jpg", "https://telegra.ph/file/683793c415fdaf5a54853.jpg", "https://telegra.ph/file/6816f11ae5d4e29b5f707.jpg", "https://telegra.ph/file/6fbd65824e787bb91f559.jpg", "https://telegra.ph/file/f578a4457abc58d34a0df.jpg", "https://telegra.ph/file/0cfbee4790d67ed15e60a.jpg", "https://telegra.ph/file/3c79fdbf38ba01b53a5da.jpg", "https://telegra.ph/file/ab665d356079e5a10cf64.jpg", "https://telegra.ph/file/554dbf1a487cf867df418.jpg", "https://telegra.ph/file/ed9e57413191355e5f284.jpg", "https://telegra.ph/file/e9a93a17bdd906faa2f5c.jpg", "https://telegra.ph/file/11287a8153f2a55db23f2.jpg", "https://telegra.ph/file/9ebf0648d04d7f6e33ae4.jpg", "https://telegra.ph/file/b0e4b8ebec47c61966519.jpg"]}

**Comment by kongicus** [comment]
不是中介，不卖房，只是记录自己看过的。
六日町駅西口走路６分种，有便利店，屋顶便于积雪滑下来，有除雪用的井，有温泉，附近也有学校。土地306平很大，建物317平，1986年7月修建，980万日元（47万人民币）。

9个房间啊！拿来开民宿吗之前看过一个这附近的房子，是因为靠近上越国际滑雪场看的一般可能说滑雪会想北海道吧，但是上越这些地方也是冬季比较老的有名度假地
