### ISSUE TITLE
2023-12-09: 芦屋市奥池南町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#71]
{"original_url": "https://www.athome.co.jp/kodate/6979787194/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 24000000, "location": [135.2969114, 34.7701489], "address": "芦屋市奥池南町", "rooms": "4SLDK", "land_area": 1.0, "floor_area": 236.62, "completed_date": "2002-12", "city": "兵庫県芦屋市", "description": "奥池南町の醍醐味「自然」を目一杯楽しむ家", "photos": ["https://telegra.ph/file/9f6d3571256d04b839632.jpg", "https://telegra.ph/file/4aa64a3ef7b35ff87a8a9.jpg", "https://telegra.ph/file/7cc3e1871b3438b2fce2c.jpg", "https://telegra.ph/file/a531fe1965aa744e450ed.jpg", "https://telegra.ph/file/70bd66c9ee7a6a836591d.jpg", "https://telegra.ph/file/dfc7f08738ab4e4a15c8c.jpg", "https://telegra.ph/file/8d9fbe74e6354b118b4c0.jpg", "https://telegra.ph/file/7871515a560e0d3120e4c.jpg", "https://telegra.ph/file/23c2f21bb1de190d44c54.jpg", "https://telegra.ph/file/f890d364d4ed80c0168ad.jpg", "https://telegra.ph/file/bf68e3d72dedc0070acf8.jpg", "https://telegra.ph/file/642a99188e53e1919bb40.jpg", "https://telegra.ph/file/bcede24106be67cfa0db7.jpg", "https://telegra.ph/file/74916a93804261c6510f9.jpg", "https://telegra.ph/file/4958d68084887889bbb1e.jpg", "https://telegra.ph/file/70b2c8328aba18e725103.jpg", "https://telegra.ph/file/99c354bb58ff125c215e9.jpg", "https://telegra.ph/file/15d2b90bd9f05ab42625f.jpg", "https://telegra.ph/file/b9efa526bb1bb5596cc1e.jpg", "https://telegra.ph/file/3a2466a5255320b0d9fc0.jpg", "https://telegra.ph/file/8c8f6bf9e81d427b979b7.jpg"]}

**Comment by kongicus** [comment]
偶尔还是看看高级住宅区的好房子
毕竟是芦屋，B格够的
建物236平，土地1228平，2002年修的，2400万日元（115万人民币）。
从芦屋城边上，往北上山，开车10分钟五六公里就到了。
这个土地面积，如果是所有权的话，这个价格不可能买得到，毕竟是芦屋。
所以这个地的性质有问题，这个地是定期借地権（賃借権），它介绍页写的，虽然有点长，但三条都挺重要的。

・地主に支払い済の保証金1400万円の権利は継承（保証金は期間満了時に返還）
已支付地主的保证金为 1400万日元的权利可以继承（保证金将在租期结束时退还）。
所以意思是，这个房子2400万日元，到时候如果没有意外发生，可以退回来1400万日元。相当于这个建筑物卖1000万日元（通货膨胀和利息因为不清楚租赁期还剩多久，算不出来）

・借地権の譲渡は可能ですが、地主の承諾要。（承諾料不要）
可以转让租赁权，但需要地主的同意（不需要支付转让费用）。

・借地期間満了時に更地返還要。
租赁期满时需要将土地恢复为空地。
借地期間47年4ヶ月，如果从这个房子修的时候2002年起算，现在过了21年了，大概还剩26年，假如是开民宿投资什么的，要把这个1000万价差赚回来的话，一年利润得33万日元多，每个月利润得两万七。而且还不止这个，还有租地的租金，每个月91000日元。到时候还要出解体费把房子拆了，还有一笔。

这种土地类型是土地投资，投资者当初买一个地，再委托中介公司把地借出去，租客盖一户建盖公寓什么的，每个月给地租，租期满了租客或者中介公司代理把地重整成平的，继续找下一个租客。这种拿来建小公寓的可能多一点。

**Comment by kongicus** [comment]
偶尔还是看看高级住宅区的好房子
毕竟是芦屋，B格够的
建物236平，土地1228平，2002年修的，2400万日元（115万人民币）。
从芦屋城边上，往北上山，开车10分钟五六公里就到了。
这个土地面积，如果是所有权的话，这个价格不可能买得到，毕竟是芦屋。
所以这个地的性质有问题，这个地是定期借地権（賃借権），它介绍页写的，虽然有点长，但三条都挺重要的。

・地主に支払い済の保証金1400万円の権利は継承（保証金は期間満了時に返還）
已支付地主的保证金为 1400万日元的权利可以继承（保证金将在租期结束时退还）。
所以意思是，这个房子2400万日元，到时候如果没有意外发生，可以退回来1400万日元。相当于这个建筑物卖1000万日元（通货膨胀和利息因为不清楚租赁期还剩多久，算不出来）

・借地権の譲渡は可能ですが、地主の承諾要。（承諾料不要）
可以转让租赁权，但需要地主的同意（不需要支付转让费用）。

・借地期間満了時に更地返還要。
租赁期满时需要将土地恢复为空地。
借地期間47年4ヶ月，如果从这个房子修的时候2002年起算，现在过了21年了，大概还剩26年，假如是开民宿投资什么的，要把这个1000万价差赚回来的话，一年利润得33万日元多，每个月利润得两万七。而且还不止这个，还有租地的租金，每个月91000日元。到时候还要出解体费把房子拆了，还有一笔。

这种土地类型是土地投资，投资者当初买一个地，再委托中介公司把地借出去，租客盖一户建盖公寓什么的，每个月给地租，租期满了租客或者中介公司代理把地重整成平的，继续找下一个租客。这种拿来建小公寓的可能多一点。
