### ISSUE TITLE
2023-12-10: さいたま市緑区大字中尾

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#72]
{"original_url": "https://www.athome.co.jp/kodate/1072368646/?DOWN=4&BKLISTID=004LPC&sref=list_map", "price": 19800000, "location": [139.681974, 35.873742], "address": "さいたま市緑区大字中尾", "rooms": "4LDK", "land_area": 100.7, "floor_area": 111.6, "completed_date": "1995-01", "city": "埼玉県さいたま市緑区", "description": "角地、高台につき日当たり・通風良好です。お気軽にお問合せください。", "photos": ["https://telegra.ph/file/685d186dbc2ff09825d2e.jpg", "https://telegra.ph/file/15201b046fa7d54edcb85.jpg", "https://telegra.ph/file/650a584898118ecd58bb8.jpg", "https://telegra.ph/file/94698ef5abe0e3564c947.jpg", "https://telegra.ph/file/c84279c58e1062a2ff2ff.jpg", "https://telegra.ph/file/c18e7e4e6b09d1df8eb3d.jpg", "https://telegra.ph/file/641d5ed978a2cddc94f97.jpg", "https://telegra.ph/file/ccfe0dccdb7642a0303ac.jpg", "https://telegra.ph/file/0f795292274f20c918a0c.jpg", "https://telegra.ph/file/15272a098baf942b62633.jpg", "https://telegra.ph/file/2bd399397786e4014c631.jpg", "https://telegra.ph/file/21d6e3a79fcce24389880.jpg", "https://telegra.ph/file/8ef9d92cca4b6d3609bb0.jpg", "https://telegra.ph/file/4f10e6e7c23784063773f.jpg", "https://telegra.ph/file/1169620fb4d0cbfff72e1.jpg", "https://telegra.ph/file/48122e9a2d6df22c2eb5f.jpg", "https://telegra.ph/file/cba080e0f32cfcda45b39.jpg", "https://telegra.ph/file/4bbadbb0660676a8b87bf.jpg", "https://telegra.ph/file/666ce84c33358d5336f41.jpg", "https://telegra.ph/file/c7a83fb7f212588d2ba0e.jpg", "https://telegra.ph/file/51f94bd8c861cce09e904.jpg", "https://telegra.ph/file/6ba791ea216e48bb957c8.jpg", "https://telegra.ph/file/8aa9522b9183b6e061da7.jpg", "https://telegra.ph/file/39d31832713ea4e33a5c8.jpg", "https://telegra.ph/file/2d304c6ec23d20f495a24.jpg", "https://telegra.ph/file/70767991d8599ccd455b0.jpg"]}

**Comment by kongicus** [comment]
土地100平，建物111.6平，1995年1月修的，1980万日元（95万人民币）。
骑自行车去车站浦和站15分钟。除了离车站远，是二手房，其他没什么很明显的缺点。离周围超市中小学都很近。
和它离车站差不多远，比它早一年修的有几栋，都挂到接近3000万日元，这一栋属于相对来说便宜的。
