### ISSUE TITLE
2023-12-13: 草加市柳島町

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#74]
{"original_url": "https://www.athome.co.jp/kodate/6980292493/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 21800000, "location": [139.7831609, 35.81654899999999], "address": "草加市柳島町", "rooms": "6LDK", "land_area": 101.15, "floor_area": 118.02, "completed_date": "1994-07", "city": "埼玉県草加市", "description": null, "photos": ["https://telegra.ph/file/8413eae328e6329452d4f.jpg", "https://telegra.ph/file/fb82809a0875b47e88144.jpg", "https://telegra.ph/file/eccc28af994dcaf83a868.jpg"]}

**Comment by kongicus** [comment]
这个不是很便宜，只能说比新筑便宜……
地101.15平，建物118.02平，房子比较大，1994年7月修的不是太老，2180万日元（105万人民币）不是太贵。
就是旁边有个小停车场，有些人可能介意这里停车场人来人往吧。
问题就是这个地段吧……说起来在足立区往北算市区吧，但刚好在見沼代親水公園駅和谷塚两个站中间，得走20分钟才能到车站。
这个見沼代親水公園駅走路20分钟的新筑大概是3000~3400万元左右吧。离车站近就不是这个价了。
