### ISSUE TITLE
2024-01-17: 春日部市藤塚

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#75]
{"original_url": "https://www.athome.co.jp/kodate/1004015380/?DOWN=8&BKLISTID=011DPC&SEARCHDIV=2&sref=member", "price": 12800000, "location": [139.778086, 35.972115], "address": "春日部市藤塚", "rooms": "3LDK", "land_area": 100.44, "floor_area": 76.17, "completed_date": "1979-09", "city": "埼玉県春日部市", "description": "敷地30坪の整形地！注文住宅用地としてもご利用頂けます(^^)/当社では一級建築士による無料の間取り作成も承ります。お気軽にご相談下さい(*^_^*)", "photos": ["https://telegra.ph/file/2b7f0acf2992966d0c55b.jpg", "https://telegra.ph/file/2194b41764f2efcd12bcb.jpg", "https://telegra.ph/file/fe093b1ae0f4d14a1abdc.jpg", "https://telegra.ph/file/3de465450e19f1e18a098.jpg", "https://telegra.ph/file/c512047235df1d442e00e.jpg", "https://telegra.ph/file/a16bcc71b7ea995b878a1.jpg", "https://telegra.ph/file/d5ef85eca3132716d82c1.jpg", "https://telegra.ph/file/e560477447d009321f284.jpg", "https://telegra.ph/file/df10bb54d4d1532f5f35d.jpg", "https://telegra.ph/file/6a9b6c9513dda7d3a6b5f.jpg", "https://telegra.ph/file/15eca1a876f945676dc76.jpg", "https://telegra.ph/file/ffabe1cd35231db66c9be.jpg", "https://telegra.ph/file/e9d300253c1d0144238db.jpg", "https://telegra.ph/file/1d88024f4780a8bcb0c77.jpg", "https://telegra.ph/file/4be5b29c59441f4ef58ae.jpg", "https://telegra.ph/file/6fed9b425be2960647e25.jpg", "https://telegra.ph/file/e7f60cc87f92fc913005d.jpg"]}

**Comment by kongicus** [comment]
上次记得看了个很便宜，还挺多人问我的，也是春日部市的，
这栋离车站藤の牛島駅走路13分钟，实际走估计15-20分钟吧，但转车不太方便，先要坐车去春日部站，再转去东京。
