### ISSUE TITLE
2024-01-18: 春日部市増富

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#76]
{"original_url": "https://www.athome.co.jp/kodate/6979590292/?BKLISTID=022LPC&sref=recommend&rcmdid=102&RECOMMFLG=1", "price": 13800000, "location": [139.7339254, 35.9675614], "address": "春日部市増富", "rooms": "5DK", "land_area": 111.69, "floor_area": 91.91, "completed_date": "1980-11", "city": "埼玉県春日部市", "description": "閑静な住宅街の戸建て登場です。生活施設が揃った住環境で暮らしやすいです。弊社から至近の物件ですので即対応可能です。土地としての販売も可能ですのでご相談ください♪", "photos": ["https://telegra.ph/file/8eeea0963b746e19f0f18.jpg", "https://telegra.ph/file/961886581e49ed8e5a707.jpg", "https://telegra.ph/file/5219b07916daf31ed342b.jpg", "https://telegra.ph/file/a435b4ebce3845fd0546b.jpg", "https://telegra.ph/file/df688626381b0ad05fb5a.jpg"]}

**Comment by kongicus** [comment]
春日部价格洼地，能这么洼，那是因为离车站远，走路去车站估计20分钟
离车站近不会这么便宜，这种要二次出售也挺难的，自己住不图以后怎么涨价还行
实际上我觉得这种能讲价，应该没有挂牌的1380万这么高
