### ISSUE TITLE
2023-10-10: 長野市篠ノ井塩崎

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#8]
{"original_url": "https://www.athome.co.jp/kodate/6978518992/?DOWN=1&BKLISTID=001LPC&sref=list_simple", "price": 13900000, "location": [138.10853587116398, 36.55106884689516], "address": "長野市篠ノ井塩崎", "rooms": "4DK", "land_area": 153.0, "floor_area": 80.32, "completed_date": "1983-03", "city": "長野県長野市", "description": "南西角地で日当たり良好！４ＤＫの内装・水廻り設備新規リフォーム済み中古住宅！建物診断（インスペクション）済み！", "photos": ["https://telegra.ph/file/eeed50dcfe1ad4545c1c4.jpg", "https://telegra.ph/file/43f70db481e014ac96dc3.jpg", "https://telegra.ph/file/3112bfd987a92a194f309.jpg", "https://telegra.ph/file/cb93b5ed51389c0a8628f.jpg", "https://telegra.ph/file/48904a198a1b4bb54ffa9.jpg", "https://telegra.ph/file/4ba2d6e659c662ab4507a.jpg", "https://telegra.ph/file/f51ae1c0eca08beda51b4.jpg", "https://telegra.ph/file/5a350d27974fa0f1d65b4.jpg", "https://telegra.ph/file/16771c3dc0298633c12fc.jpg", "https://telegra.ph/file/34de6dbe4a1b9e81fef6d.jpg", "https://telegra.ph/file/e0b14b8229132810855b8.jpg", "https://telegra.ph/file/e8966db57e193709edab8.jpg", "https://telegra.ph/file/3a4faea12c0ae07372d76.jpg", "https://telegra.ph/file/fc2f043e9044985c489e8.jpg"]}

**Comment by kongicus** [comment]
离车站走路4分钟，离长野市中心开车25分钟，电车40分钟，走路3分钟去最近的菜店，走路10分钟有711。

今年9月全部翻新过。

附近玩的自然是登山，稲荷山位于长野县长野市，海拔约419米，离市区很近，拥有丰富的历史和自然风光。山坡上有着稲荷神社，自古以来一直是信仰的中心。许多人前来祈愿。特别是在初詣时，有很多游客前来参拜。
稲荷山对爱好徒步旅行的人来说是一个绝佳的地方。山路已经修整好，相对容易攀登。从山顶可以俯瞰城市和周围的山脉。
