### ISSUE TITLE
2023-10-10: 埼玉県春日部市東中野

### ISSUE THREAD

**Issue by TheodoreKrypton** [TheodoreKrypton/jp-homes-page#9]
{"original_url": "https://suumo.jp/chukoikkodate/saitama/sc_kasukabe/nc_73192475/", "price": 11800000, "location": [139.8195695884, 35.97580729458], "address": "埼玉県春日部市東中野", "rooms": "4LDK", "land_area": 128.5, "floor_area": 102.47, "completed_date": "1997-11", "city": "春日部市", "description": "閑静な住宅街の住戸、更に部屋の換気もしやすい２面採光のある住戸なので、自然光が部屋に差し込みます。\nまた広々とした延床面積１０２．４７平米の居室空間で、その上お料理に集中できる独立型キッチン仕様だから、台所が散らかっていても人目にふれません。\nちなみに一度に複数のおかず作りを同時進行できるコンロ３口以上付です。\n家族の物語が生まれる４ＬＤＫ。ご案内いたしますのでお気軽にご連絡ください。", "photos": ["https://telegra.ph/file/34948178b284e9724f1cf.jpg", "https://telegra.ph/file/20689d57b129b83ebc237.jpg", "https://telegra.ph/file/70781ca151de1afc12523.jpg", "https://telegra.ph/file/87112235ab7068a2b3799.jpg", "https://telegra.ph/file/1f445813866895cc54267.jpg"]}

**Comment by kongicus** [comment]
坐电车去东京1小时，开车也差不多1小时，在江户川河边上。
一千万出头挂得低了，很奇怪，东中野这个地段，建物100平的话，二手如果最近二十年基本上是两千多万一栋。新筑3500万多。这个地段80平的二手才能有1500万这个价。

角地两面采光，方便通风。
总面积为102.47平方米，独立厨房，三个灶眼。
